/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Expanded details for the URL specified in the User's profile, with start and end indices.
type UserEntitiesUrl struct {
	Urls []UrlEntity `json:"urls,omitempty"`
}
