/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A list of metadata found in the User's profile description.
type UserEntities struct {
	Description *FullTextEntities `json:"description,omitempty"`
	Url         *UserEntitiesUrl  `json:"url,omitempty"`
}
