/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Tweet compliance data.
type TweetComplianceData struct {
	TweetDeleteComplianceSchema
	TweetWithheldComplianceSchema
	TweetDropComplianceSchema
	TweetUndropComplianceSchema
	TweetEditComplianceSchema
}
