/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A response from deleting user-specified stream filtering rules.
type DeleteRulesRequest struct {
	Delete *DeleteRulesRequestDelete `json:"delete"`
}
