/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represent the portion of text recognized as a Cashtag, and its start and end position within the text.
type CashtagFields struct {
	Tag string `json:"tag"`
}
