/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type ComplianceJob struct {
	CreatedAt         *time.Time           `json:"created_at"`
	DownloadExpiresAt *time.Time           `json:"download_expires_at"`
	DownloadUrl       string               `json:"download_url"`
	Id                string               `json:"id"`
	Name              string               `json:"name,omitempty"`
	Status            *ComplianceJobStatus `json:"status"`
	Type_             *ComplianceJobType   `json:"type"`
	UploadExpiresAt   *time.Time           `json:"upload_expires_at"`
	UploadUrl         string               `json:"upload_url"`
}
