/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Nonpublic engagement metrics for the Tweet at the time of the request.
type TweetNonPublicMetrics struct {
	// Number of times this Tweet has been viewed.
	ImpressionCount int32 `json:"impression_count,omitempty"`
}
