/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A user-provided stream filtering rule.
type RuleNoId struct {
	Tag   string `json:"tag,omitempty"`
	Value string `json:"value"`
}
