/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Geo struct {
	Bbox       []float64    `json:"bbox"`
	Geometry   *Point       `json:"geometry,omitempty"`
	Properties *interface{} `json:"properties"`
	Type_      string       `json:"type"`
}
