/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represent the information for the URL image.
type UrlImage struct {
	Height int32  `json:"height,omitempty"`
	Url    string `json:"url,omitempty"`
	Width  int32  `json:"width,omitempty"`
}
