/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Expansions struct {
	Media  []Media `json:"media,omitempty"`
	Places []Place `json:"places,omitempty"`
	Polls  []Poll  `json:"polls,omitempty"`
	Topics []Topic `json:"topics,omitempty"`
	Tweets []Tweet `json:"tweets,omitempty"`
	Users  []User  `json:"users,omitempty"`
}
