/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents the data for the context annotation entity.
type ContextAnnotationEntityFields struct {
	// Description of the context annotation entity.
	Description string `json:"description,omitempty"`
	// The unique id for a context annotation entity.
	Id string `json:"id"`
	// Name of the context annotation entity.
	Name string `json:"name,omitempty"`
}
