/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ComplianceJobType : Type of compliance job to list.
type ComplianceJobType string

// List of ComplianceJobType
const (
	TWEETS_ComplianceJobType ComplianceJobType = "tweets"
	USERS_ComplianceJobType  ComplianceJobType = "users"
)
