/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country).
type TweetWithheld struct {
	// Indicates if the content is being withheld for on the basis of copyright infringement.
	Copyright bool `json:"copyright"`
	// Provides a list of countries where this content is not available.
	CountryCodes []string `json:"country_codes"`
	// Indicates whether the content being withheld is the `tweet` or a `user`.
	Scope string `json:"scope,omitempty"`
}
