/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TweetCreateRequest struct {
	// Card Uri Parameter. This is mutually exclusive from Quote Tweet Id, Poll, Media, and Direct Message Deep Link.
	CardUri string `json:"card_uri,omitempty"`
	// Link to take the conversation from the public timeline to a private Direct Message.
	DirectMessageDeepLink string `json:"direct_message_deep_link,omitempty"`
	// Exclusive Tweet for super followers.
	ForSuperFollowersOnly bool                     `json:"for_super_followers_only,omitempty"`
	Geo                   *TweetCreateRequestGeo   `json:"geo,omitempty"`
	Media                 *TweetCreateRequestMedia `json:"media,omitempty"`
	// Nullcasted (promoted-only) Tweets do not appear in the public timeline and are not served to followers.
	Nullcast     bool                     `json:"nullcast,omitempty"`
	Poll         *TweetCreateRequestPoll  `json:"poll,omitempty"`
	QuoteTweetId string                   `json:"quote_tweet_id,omitempty"`
	Reply        *TweetCreateRequestReply `json:"reply,omitempty"`
	// Settings to indicate who can reply to the Tweet.
	ReplySettings string `json:"reply_settings,omitempty"`
	Text          string `json:"text,omitempty"`
}
