/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// IDs and values of all deleted user-specified stream filtering rules.
type DeleteRulesRequestDelete struct {
	// IDs of all deleted user-specified stream filtering rules.
	Ids []string `json:"ids,omitempty"`
	// Values of all deleted user-specified stream filtering rules.
	Values []string `json:"values,omitempty"`
}
