/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The location tagged on the Tweet, if the user provided one.
type TweetGeo struct {
	Coordinates *Point `json:"coordinates,omitempty"`
	PlaceId     string `json:"place_id,omitempty"`
}
