/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A problem that indicates your client is forbidden from making this request.
type ClientForbiddenProblem struct {
	Detail          string `json:"detail,omitempty"`
	Status          int32  `json:"status,omitempty"`
	Title           string `json:"title"`
	Type_           string `json:"type"`
	Reason          string `json:"reason,omitempty"`
	RegistrationUrl string `json:"registration_url,omitempty"`
}
