/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type Tweet struct {
	Attachments        *TweetAttachments   `json:"attachments,omitempty"`
	AuthorId           string              `json:"author_id,omitempty"`
	ContextAnnotations []ContextAnnotation `json:"context_annotations,omitempty"`
	ConversationId     string              `json:"conversation_id,omitempty"`
	// Creation time of the Tweet.
	CreatedAt    time.Time          `json:"created_at,omitempty"`
	EditControls *TweetEditControls `json:"edit_controls,omitempty"`
	// A list of Tweet Ids in this Tweet chain.
	EditHistoryTweetIds []string          `json:"edit_history_tweet_ids"`
	Entities            *FullTextEntities `json:"entities,omitempty"`
	Geo                 *TweetGeo         `json:"geo,omitempty"`
	Id                  string            `json:"id"`
	InReplyToUserId     string            `json:"in_reply_to_user_id,omitempty"`
	// Language of the Tweet, if detected by Twitter. Returned as a BCP47 language tag.
	Lang             string                 `json:"lang,omitempty"`
	NonPublicMetrics *TweetNonPublicMetrics `json:"non_public_metrics,omitempty"`
	OrganicMetrics   *TweetOrganicMetrics   `json:"organic_metrics,omitempty"`
	// Indicates if this Tweet contains URLs marked as sensitive, for example content suitable for mature audiences.
	PossiblySensitive bool                  `json:"possibly_sensitive,omitempty"`
	PromotedMetrics   *TweetPromotedMetrics `json:"promoted_metrics,omitempty"`
	PublicMetrics     *TweetPublicMetrics   `json:"public_metrics,omitempty"`
	// A list of Tweets this Tweet refers to. For example, if the parent Tweet is a Retweet, a Quoted Tweet or a Reply, it will include the related Tweet referenced to by its parent.
	ReferencedTweets []TweetReferencedTweets `json:"referenced_tweets,omitempty"`
	ReplySettings    *ReplySettings          `json:"reply_settings,omitempty"`
	// The name of the app the user Tweeted from.
	Source   string         `json:"source,omitempty"`
	Text     string         `json:"text"`
	Withheld *TweetWithheld `json:"withheld,omitempty"`
}
