/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type TweetUnviewable struct {
	// If the label is being applied or removed. Possible values are ‘apply’ or ‘remove’.
	Application string `json:"application"`
	// Event time.
	EventAt time.Time                   `json:"event_at"`
	Tweet   *TweetComplianceSchemaTweet `json:"tweet"`
}
