/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlaceType string

// List of PlaceType
const (
	POI_PlaceType          PlaceType = "poi"
	NEIGHBORHOOD_PlaceType PlaceType = "neighborhood"
	CITY_PlaceType         PlaceType = "city"
	ADMIN_PlaceType        PlaceType = "admin"
	COUNTRY_PlaceType      PlaceType = "country"
	UNKNOWN_PlaceType      PlaceType = "unknown"
)
