/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represent the portion of text recognized as a URL, and its start and end position within the text.
type UrlEntity struct {
	// Description of the URL landing page.
	Description string `json:"description,omitempty"`
	// The URL as displayed in the Twitter client.
	DisplayUrl  string     `json:"display_url,omitempty"`
	ExpandedUrl string     `json:"expanded_url,omitempty"`
	Images      []UrlImage `json:"images,omitempty"`
	MediaKey    string     `json:"media_key,omitempty"`
	Status      int32      `json:"status,omitempty"`
	// Title of the page the URL points to.
	Title string `json:"title,omitempty"`
	// Fully resolved url.
	UnwoundUrl string `json:"unwound_url,omitempty"`
	Url        string `json:"url"`
	// Index (zero-based) at which position this entity ends.  The index is exclusive.
	End int32 `json:"end"`
	// Index (zero-based) at which position this entity starts.  The index is inclusive.
	Start int32 `json:"start"`
}
