/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Poll options for a Tweet with a poll. This is mutually exclusive from Media, Quote Tweet Id, and Card URI.
type TweetCreateRequestPoll struct {
	// Duration of the poll in minutes.
	DurationMinutes int32    `json:"duration_minutes"`
	Options         []string `json:"options"`
	// Settings to indicate who can reply to the Tweet.
	ReplySettings string `json:"reply_settings,omitempty"`
}
