/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// A Twitter List is a curated group of accounts.
type List struct {
	CreatedAt     time.Time `json:"created_at,omitempty"`
	Description   string    `json:"description,omitempty"`
	FollowerCount int32     `json:"follower_count,omitempty"`
	Id            string    `json:"id"`
	MemberCount   int32     `json:"member_count,omitempty"`
	// The name of this List.
	Name    string `json:"name"`
	OwnerId string `json:"owner_id,omitempty"`
	Private bool   `json:"private,omitempty"`
}
