/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Place ID being attached to the Tweet for geo location.
type TweetCreateRequestGeo struct {
	PlaceId string `json:"place_id,omitempty"`
}
