/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type TweetEditComplianceObjectSchema struct {
	EditTweetIds []string `json:"edit_tweet_ids"`
	// Event time.
	EventAt        time.Time                             `json:"event_at"`
	InitialTweetId string                                `json:"initial_tweet_id"`
	Tweet          *TweetEditComplianceObjectSchemaTweet `json:"tweet"`
}
