/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Media information being attached to created Tweet. This is mutually exclusive from Quote Tweet Id, Poll, and Card URI.
type TweetCreateRequestMedia struct {
	// A list of Media Ids to be attached to a created Tweet.
	MediaIds []string `json:"media_ids"`
	// A list of User Ids to be tagged in the media for created Tweet.
	TaggedUserIds []string `json:"tagged_user_ids,omitempty"`
}
