/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FullTextEntities struct {
	Annotations []AllOfFullTextEntitiesAnnotationsItems `json:"annotations,omitempty"`
	Cashtags    []CashtagEntity                         `json:"cashtags,omitempty"`
	Hashtags    []HashtagEntity                         `json:"hashtags,omitempty"`
	Mentions    []MentionEntity                         `json:"mentions,omitempty"`
	Urls        []UrlEntity                             `json:"urls,omitempty"`
}
