/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Engagement metrics for the Media at the time of the request.
type VideoPublicMetrics struct {
	// Number of times this video has been viewed.
	ViewCount int32 `json:"view_count,omitempty"`
}
