/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type TweetEditControls struct {
	// Time when Tweet is no longer editable.
	EditableUntil time.Time `json:"editable_until"`
	// Number of times this Tweet can be edited.
	EditsRemaining int32 `json:"edits_remaining"`
	// Indicates if this Tweet is eligible to be edited.
	IsEditEligible bool `json:"is_edit_eligible"`
}
