/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A Twitter List is a curated group of accounts.
type ListCreateResponseData struct {
	Id string `json:"id"`
	// The name of this List.
	Name string `json:"name"`
}
