/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type UserComplianceSchema struct {
	// Event time.
	EventAt time.Time                 `json:"event_at"`
	User    *UserComplianceSchemaUser `json:"user"`
}
