/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Variant struct {
	// The bit rate of the media.
	BitRate int32 `json:"bit_rate,omitempty"`
	// The content type of the media.
	ContentType string `json:"content_type,omitempty"`
	// The url to the media.
	Url string `json:"url,omitempty"`
}
