/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represent the portion of text recognized as a Hashtag, and its start and end position within the text.
type HashtagFields struct {
	// The text of the Hashtag.
	Tag string `json:"tag"`
}
