/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type UserScrubGeoObjectSchema struct {
	// Event time.
	EventAt     time.Time                 `json:"event_at"`
	UpToTweetId string                    `json:"up_to_tweet_id"`
	User        *UserComplianceSchemaUser `json:"user"`
}
