/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserUndeleteComplianceSchema struct {
	UserUndelete *UserComplianceSchema `json:"user_undelete"`
}
