/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ComplianceJobStatus : Status of a compliance job.
type ComplianceJobStatus string

// List of ComplianceJobStatus
const (
	CREATED_ComplianceJobStatus     ComplianceJobStatus = "created"
	IN_PROGRESS_ComplianceJobStatus ComplianceJobStatus = "in_progress"
	FAILED_ComplianceJobStatus      ComplianceJobStatus = "failed"
	COMPLETE_ComplianceJobStatus    ComplianceJobStatus = "complete"
	EXPIRED_ComplianceJobStatus     ComplianceJobStatus = "expired"
)
