/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A request to create a new batch compliance job.
type CreateComplianceJobRequest struct {
	Name string `json:"name,omitempty"`
	// If true, this endpoint will return a pre-signed URL with resumable uploads enabled.
	Resumable bool `json:"resumable,omitempty"`
	// Type of compliance job to list.
	Type_ string `json:"type"`
}
