/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A request to add a user-specified stream filtering rule.
type AddRulesRequest struct {
	Add []RuleNoId `json:"add"`
}
