/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type UserProfileModificationObjectSchema struct {
	// Event time.
	EventAt      time.Time                 `json:"event_at"`
	NewValue     string                    `json:"new_value"`
	ProfileField string                    `json:"profile_field"`
	User         *UserComplianceSchemaUser `json:"user"`
}
