/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UsersFollowingCreateResponseData struct {
	Following     bool `json:"following,omitempty"`
	PendingFollow bool `json:"pending_follow,omitempty"`
}
