/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TweetEditComplianceSchema struct {
	TweetEdit *TweetEditComplianceObjectSchema `json:"tweet_edit"`
}
