/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A list of metrics for this User.
type UserPublicMetrics struct {
	// Number of Users who are following this User.
	FollowersCount int32 `json:"followers_count"`
	// Number of Users this User is following.
	FollowingCount int32 `json:"following_count"`
	// The number of lists that include this User.
	ListedCount int32 `json:"listed_count"`
	// The number of Tweets (including Retweets) posted by this User.
	TweetCount int32 `json:"tweet_count"`
}
