/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.54
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Annotation for entities based on the Tweet text.
type AllOfFullTextEntitiesAnnotationsItems struct {
	// Index (zero-based) at which position this entity ends.  The index is inclusive.
	End int32 `json:"end"`
	// Index (zero-based) at which position this entity starts.  The index is inclusive.
	Start int32 `json:"start"`
	// Text used to determine annotation.
	NormalizedText string `json:"normalized_text,omitempty"`
	// Confidence factor for annotation type.
	Probability float64 `json:"probability,omitempty"`
	// Annotation type.
	Type_ string `json:"type,omitempty"`
}
